name: cem_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Added Google Fonts package
  google_fonts: ^6.1.0

  # ✅ Added Font Awesome Flutter package
  font_awesome_flutter: ^10.1.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true